sonar.organization=cks-solutions
sonar.projectKey=CKS-Solutions_fast-food-auth-api
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/*_test.go,**/*.zip,**/terraform/**,**/node_modules/**,**/.github/**,**/*.md,**/go.sum
sonar.coverage.exclusions=**/*_test.go,**/coverage.html
sonar.go.coverage.reportPaths=src/auth/coverage.out
