name: CICD

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  id-token: write

concurrency:
  group: prod-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  AWS_REGION: us-east-1

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.PROD_AWS_ACCOUNT_ID }}:role/GitHubActionsDeployRole
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: gha-${{ github.run_id }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.1'

      - name: Build Go Lambda function
        run: |
          cd src/auth
          go mod download
          GOOS=linux GOARCH=amd64 go build -o main main.go
          zip auth.zip main

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -input=false -backend-config="envs/prod/backend.hcl"

      - name: Terraform Plan
        working-directory: terraform
        run: |
          terraform plan -input=false \
            -var aws_region=${{ env.AWS_REGION }} \
            -var expected_account_id=${{ vars.PROD_AWS_ACCOUNT_ID }} \
            -var jwt_secret=${{ secrets.JWT_SECRET }} \
            -var environment=production

  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs: plan

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.PROD_AWS_ACCOUNT_ID }}:role/GitHubActionsDeployRole
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: gha-${{ github.run_id }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.1'

      - name: Build Go Lambda function
        run: |
          cd src/auth
          go mod download
          GOOS=linux GOARCH=amd64 go build -o main main.go
          zip auth.zip main

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -input=false -backend-config="envs/prod/backend.hcl"

      - name: Terraform Apply
        working-directory: terraform
        run: |
          terraform apply -input=false -auto-approve \
            -var aws_region=${{ env.AWS_REGION }} \
            -var expected_account_id=${{ vars.PROD_AWS_ACCOUNT_ID }} \
            -var jwt_secret=${{ secrets.JWT_SECRET }} \
            -var environment=production
